- name: INSTALL HTTPD (CentOS)
  tags: centos, httpd
  package:
    name:
      - "{{ apache_package_name }}" 
      - "{{ php_package_name }}"
    state: present
  when: ansible_distribution == "CentOS"

- name: Start HTTPD and Enable it (CentOS)
  tags: centos, httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
       

- name: Change the parameters in index file (Centos)
  tags: centos, httpd
  lineinfile: 
    path: /var/www/html/index.html
    regexp: 'Patko.bily@gmail.com'
    firstmatch: yes
    line: <p> Patko.bily@gmail.com.01 </p>
  when: ansible_distribution == "CentOS"
  notify: restart_apache_server
