---
- name: install xfce packages
  tags: configuration
  dnf:
    name: 
      - "{{ desktop_xfce4_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "9"

- name: enable gdm service
  tags: configuration
  systemd:
    name: gdm
    enabled: true
    state: started

- name: Set default target to graphical.target using shell
  shell: systemctl set-default graphical.target 
  args:
    executable: /bin/bash
  failed_when: false

- name: Copy xfce configuration files to force xfce as default desktop environment
  tags: configuration
  copy:
    src: /xfce/files/standard
    dest: /etc/accountsservice/user-templates/standard
    owner: root
    group: root
    mode: "0644"
 
- name: Hide user options to choose other desktop environments than xfce
  tags: configuration
  lineinfile:
    path: "{{ item }}"
    regexp: '^#?WaylandEnable='
    line: 'WaylandEnable=false'
  with_items:
    - /etc/gdm/custom.conf

- name: Create a DIRs
  tags: configuration
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755" 
  loop: 
    - /etc/xdg/autostart
    - /etc/skel/Desktop
    - /usr/share/xsessions.disabled
    - ~/.config/autostart

- name: Create a Launcher direcrories
  ansible.builtin.file:
    dest: /etc/skel/.config/xfce4/panel/launcher-{{ item }}
    state: directory
    owner: root
    group: root
    mode: "0755"
  with_sequence: start=20 end=23 format=/etc/skel/.config/xfce4/panel/launcher-format=%02d 

- name: Copy launchers setting to the direcrories
  copy:
    src: /launcher/
    dest: /etc/skel/.config/xfce4/panel/launcher-{{ item }}/
    owner: root
    group: root
    mode: "0664"
  with_sequence: start=20 end=23 format=%02d
  
- name: Look if the folder contains the files
  find:
    path: /usr/share/xsessions
    file_type: file
    patterns: "*.desktop"
    excludes: "xfce.desktop"
  register: desktopfile  

- name: Move unused sessions (excluding xfce.desktop)
  command:
    cmd: mv "{{ item.path }}" /usr/share/xsessions.disabled/
  loop: "{{ desktopfile.files }}"
  when: desktopfile.files

# - name: Copy conky autostart file to /etc/xdg/autostart
#   tags: configuration
#   copy:
#     src: "{{ item.src}}"
#     dest: "{{ item.dest }}"
#     owner: root
#     group: root
#     mode: "0644"
#   loop:
#     - { src: /home/patrik/Ansible_tutorial/playbooks/roles/xfce/files/conky/conky.desktop, dest: /etc/xdg/autostart/conky.desktop }
#     - { src: /home/patrik/Ansible_tutorial/playbooks/roles/xfce/files/conky/conky.desktop, dest: ~/.config/autostart/conky.desktop }

- name: Copy Shortcut to /etc/skel/Desktop
  tags: configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0755"
  with_items:
     - { src: /shortcuts/Firefox.desktop, dest: /etc/skel/Desktop/Firefox.desktop }
     - { src: /shortcuts/Terminal.desktop, dest: /etc/skel/Desktop/Terminal.desktop }
     - { src: /shortcuts/Application Finder.desktop, dest: /etc/skel/Desktop/Application Finder.desktop }

- name: Copy launcher keyboard setting 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0664"
  with_items: 
    - { src: /launcher/keyboard-settings.desktop, dest: /etc/skel/.config/xfce4/panel/launcher-20/keyboard-settings.desktop }
    - { src: /launcher/firefox.desktop, dest: /etc/skel/.config/xfce4/panel/launcher-21/firefox.desktop }
    - { src: /launcher/terminal.desktop, dest: /etc/skel/.config/xfce4/panel/launcher-22/terminal.desktop }
    
- name: copy template for control panel menu
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - { src: xfce4-panel.j2, dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml }
    - { src: xfce4-desktop.j2, dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml }
    - { src: keyboard-layout.j2, dest: /etc/xdg/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml }
    - { src: whisper-menu.j2, dest: /etc/xdg/xfce4/panel/whiskermenu-1.rc }
    # - { src: conky.j2, dest: /etc/conky/conky.conf }
  notify: restart gdm
    



