---

- name: add a firefox website to the default bookmarks
  tags: firefox
  theforeman.foreman.bookmark:
    username: "patrik"
    password: "cokolada"
    server_url: https://www.ansible.com/
    name: "skuska_cez_ansible"
    query: "started_at > '12 hours ago'"
    controller: "job_invocations"
    user: patrik
    state: present
