- name: Create DIRs for launcher
  tags: configuration
  file:
    path: "{{ item}}"
    state: directory
    owner: root
    group: root
    mode: "0644" 
  loop:  
    - /etc/xdg/xfce4/panel/launcher-10

- name: Copy launcher keyboard setting 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0664"
  with_items: 
    - { src: /home/patrik/Ansible_tutorial/playbooks/roles/xfce/files/launcher/, dest: /etc/xdg/xfce4/panel/launcher-10/xfce4-terminal.desktop }

- name: link the launcher
  command:
    cmd: ln -s /etc/xdg/xfce4/panel/launcher-10 ~/.config/xfce4/panel/launcher-10