---
- name: Using template, create a remote file that contains all variables available t othe play
  template:
    src: dump_variables.j2
    dest: /tmp/ansible_variables

- name: Fetch the file with all variables to the control node
  fetch:
    src: /tmp/ansible_variables
    dest:  "/home/admin/capture_variables/{{ ansible_hostname }}"
    flat: true

- name: Clean up the left over file on the remote host
  file:
    name: /tmp/ansible_variables
    state: absent
