- name: Add user Simon
  tags: always
  user:
    name: simon
    groups: root


- name: Add ssh key for Simon
  tags: always, ssh-key
  authorized_key:
    user: simon
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOo1JA/Cp9Bdxs0vVr6yd7urXYReA03h8VoU+Opf1Bxb ANSIBLE"


- name: Add sudoers file for Simon
  tags: always, sudo
  copy:
    src: sudoer_simon
    dest: /etc/sudoers.d/simon
    owner: root
    group: root
    mode: 0440

