---


  - hosts: all
    become: true
    tasks:

    - name: Update packages (CentOs)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
      

    - name: Update packages (Debian, Ubuntu)
      tags: alawys
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Add user for Ansible (simon)
      tags: always
      user: 
        name: simon
        groups: root

    - name: copy ssh key for Simon account
      tags: always
      authorized_key:
        user: simon
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOo1JA/Cp9Bdxs0vVr6yd7urXYReA03h8VoU+Opf1Bxb ANSIBLE" 
        

    - name: Add user simon to sudoers file
      copy: 
        src: sudoer_simon
        dest: /etc/sudoers.d/simon
        owner: root
        group: root
        mode: 0440        
  
