---
- name: Remove multiple users
  hosts: all
  become: true
  tasks:
    - name: Create a users
      user:
        name: "{{ item }}"
        state: absent
      with_items:
        - john
        - jane
        - joe

  