---

  - hosts: all
    become: true
    tasks:
    
    - name: Update repo-cache (CentOS)
      tags: always
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"


    - name: Update repo-cache (Debian, Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false 
      when: ansible_distribution in ["Debian", "Ubuntu"]


    - name: Add user Simon
      tags: always
      user:
        name: simon
        groups: root


    - name: Add ssh key for Simon
      tags: always, ssh-key
      authorized_key:
        user: simon
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOo1JA/Cp9Bdxs0vVr6yd7urXYReA03h8VoU+Opf1Bxb ANSIBLE"
        

    - name: Add sudoers file for Simon
      tags: always, sudo
      copy:
        src: sudoer_simon
        dest: /etc/sudoers.d/simon
        owner: root
        group: root        
        mode: 0440





  - hosts: Repo_servers
    become: true
    tasks:

    - name: INSTALL HTTPD (CentOS)
      tags: centos, httpd
      dnf:
        name: 
          - httpd
          - php
        state: present
      when: ansible_distribution == "CentOS"


    - name: Start HTTPD and Enable it (CentOS)
      tags: centos, httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "CentOS"
       

    - name: Change the parameters in index file (Centos)
      tags: centos, httpd
      lineinfile: 
        path: /var/www/html/index.html
        regexp: 'Ansible is awesome'
        firstmatch: yes
        line: <p> Patko.bily@gmail.com </p>
      when: ansible_distribution == "CentOS"
      register: premenna





    - name: Restart HTTPD (CentoOS)
      service:
        name: httpd
        state: restarted
      when: premenna.changed


 
  - hosts: DEBIAN_servers
    become: true
    tasks: 
 
    - name: INSTALL apache2 (Debian, Ubuntu)
      tags: apache, apache2
      apt:
        name: apache2
        state: present
      when: ansible_distribution in ["Debian", "Ubuntu"]


    - name: Start apache2 (Debian, Ubuntu)
      tags: apache, apache2
      service:
        name: apache2
        state: started
        enabled: yes
      when: ansible_distribution in ["Debian", "Ubuntu"] 
 

    - name: Change the name in the file (Debian, Ubuntu)
      tags: apache, apache2
      lineinfile:
        path: /var/www/html/index.html
        regexp: 'Web-site test'
        firstmatch: yes
        line: <title>Skusobna webova stranka</title>
      when: ansible_distribution in ["Debian", "Ubuntu"]
      register: apache
   
    - name: Restart apache (Debian, Ubuntu)
      tags: apache, apache2
      service:
        name: apache2
        state: restarted
      when: apache.changed





